---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/rug-archive"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.18.1"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.2.0"
  origin:
    repo: "git@github.com-personal:atomist-rugs/rug-archive"
    branch: "jessitron/max-rug-v"
    sha: "77e40f7"
  parameters:
    - "project_name": "rug-upgrade"

---
kind: "operation"
client: "rug-cli 0.18.1"
editor:
  name: "atomist-rugs.rug-upgrade.ConvertRugToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"
  parameters:
    - "rug_name": "UpgradeFrom0_7_1"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.7.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "d4472b2bb05c009fa7e4c6657654623a5af70c23"
    sha: "d4472b2"
  parameters:
    - "repo_slug": "atomist-rugs/rug-upgrade"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

