// Generated by Rug to TypeScript transpiler.
// To take ownership of this file, simply delete the .rug file
"use strict";
var RugOperation_1 = require("@atomist/rug/operations/RugOperation");
/**
       breaking change from PR 112
*/
var UpgradeFrom0_7_1 = (function () {
    function UpgradeFrom0_7_1() {
        this.name = "UpgradeFrom0_7_1";
        this.description = "breaking change from PR 112";
    }
    UpgradeFrom0_7_1.prototype.edit = function (project) {
        var eng = project.context().pathExpressionEngine();
        var p = project;
        if (true) {
            eng.with(p, '//File()', function (f) {
                if (f.name().indexOf(".rug") > 0) {
                    f.replace("with file", "with File");
                    f.replace("with project", "with Project");
                    f.replace("with java.class", "with JavaType");
                    f.replace("with java.source", "with JavaSource");
                    f.replace("with pom", "with Pom");
                    f.replace("with elm.module", "with ElmModule");
                }
            });
        }
        return new RugOperation_1.Result(RugOperation_1.Status.Success, 'Editor [UpgradeFrom0_7_1] executed OK');
    };
    return UpgradeFrom0_7_1;
}());
var editor = new UpgradeFrom0_7_1();
