# Copyright © 2017 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Feature: Tests from TestsToTypeScript.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: TestsToTypeScript converts sample test

    Given a file named .atomist/tests/Sample.rt for TestsToTypeScript converts sample test
    When TestsToTypeScript for TestsToTypeScript converts sample test
    Then fileExists .atomist/tests/project/SampleTest.feature for TestsToTypeScript converts sample test
    Then fileExists .atomist/tests/project/SampleTest.ts for TestsToTypeScript converts sample test


  Scenario: TestsToTypeScript converts archive tests

    Given archive root for TestsToTypeScript converts archive tests
    When TestsToTypeScript for TestsToTypeScript converts archive tests
    Then no change for TestsToTypeScript converts archive tests
