# Copyright © 2017 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Feature: Tests from TestsToTypeScript.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: TestsToTypeScript converts sample test
    Given a sample DSL test
    When TestsToTypeScript edits the project
    Then the sample feature files exists
    Then the sample feature file starts with an empty project
    Then the sample feature file asserts no change
    Then the sample TypeScript test file exists


  Scenario: TestsToTypeScript converts archive tests
    Given the archive root
    When TestsToTypeScript edits the project
    Then no changes were made
