# Copyright © 2017 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Feature: Tests from UpdateRugVersion.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: UpdateRugVersion should update the version in a manifest.yml

    Given a file named .atomist/manifest.yml for UpdateRugVersion should update the version in a manifest.yml
    When UpdateRugVersion manifest_version is v, package_version is ~11.9.2 for UpdateRugVersion should update the version in a manifest.yml
    Then fileContains atomist manifest yml requires v for UpdateRugVersion should update the version in a manifest yml
    Then not result fileContains atomist manifest yml 0 6 0 for UpdateRugVersion should update the version in a manifest yml
    Then not result fileContains atomist manifest yml 11 9 2 for UpdateRugVersion should update the version in a manifest yml


  Scenario: UpdateRugVersion should update to version range in a manifest.yml

    Given a file named .atomist/manifest.yml for UpdateRugVersion should update to version range in a manifest.yml
    When UpdateRugVersion manifest_version is v, package_version is ~11.9.2 for UpdateRugVersion should update to version range in a manifest.yml
    Then fileContains atomist manifest yml requires v for UpdateRugVersion should update to version range in a manifest yml
    Then not result fileContains atomist manifest yml 0 6 0 for UpdateRugVersion should update to version range in a manifest yml
    Then not result fileContains atomist manifest yml 11 9 2 for UpdateRugVersion should update to version range in a manifest yml


  Scenario: UpdateRugVersion should update the version in a package.json

    Given a file named .atomist/manifest.yml for UpdateRugVersion should update the version in a package.json
    Given a file named .atomist/package.json for UpdateRugVersion should update the version in a package.json
    When UpdateRugVersion manifest_version is v, package_version is ~11.9.2 for UpdateRugVersion should update the version in a package.json
    Then fileContains atomist package json atomist rug 11 9 2 for UpdateRugVersion should update the version in a package json
    Then fileContains atomist package json college dtc 3 5 7 for UpdateRugVersion should update the version in a package json
    Then not result fileContains atomist package json 0 6 0 for UpdateRugVersion should update the version in a package json
    Then not result fileContains atomist package json v for UpdateRugVersion should update the version in a package json


  Scenario: UpdateRugVersion should update the version in a squashed package.json

    Given a file named .atomist/manifest.yml for UpdateRugVersion should update the version in a squashed package.json
    Given a file named .atomist/package.json for UpdateRugVersion should update the version in a squashed package.json
    When UpdateRugVersion for UpdateRugVersion should update the version in a squashed package.json
    Then fileContains atomist package json atomist rug 11 9 2 for UpdateRugVersion should update the version in a squashed package json
    Then fileContains atomist package json college dtc 3 5 7 for UpdateRugVersion should update the version in a squashed package json
    Then not result fileContains atomist package json 0 6 0 for UpdateRugVersion should update the version in a squashed package json
    Then not result fileContains atomist package json manifest version for UpdateRugVersion should update the version in a squashed package json


  Scenario: UpdateRugVersion should do nothing if not a Rug Archive project

    Given nothing for UpdateRugVersion should do nothing if not a Rug Archive project
    When UpdateRugVersion manifest_version is v, package_version is ~11.9.2 for UpdateRugVersion should do nothing if not a Rug Archive project
    Then no change for UpdateRugVersion should do nothing if not a Rug Archive project
